### ISSUE TITLE
[bug] 部分遊戲在 showcase 頁面不會正常上色

### ISSUE THREAD

**Issue by bestpika** [HCLonely/IG-Helper#5]
<https://supertotalcarnage.indiegala.com/>
![image](https://user-images.githubusercontent.com/5698157/198874323-5cb457c6-61fa-4e5a-bbbe-fa5e1d06a976.png)
![image](https://user-images.githubusercontent.com/5698157/198874330-4ecc00fb-2950-4d25-8d1b-9a52cac4e664.png)

**Comment by HCLonely** [comment]
你的意思是第二张图那样不上色吗

**Comment by bestpika** [comment]
第一張圖只是表示他有在庫裡面
第二張圖才是問題點

**Comment by HCLonely** [comment]
第二张图是哪个页面？

**Comment by bestpika** [comment]
Showcase
![image](https://user-images.githubusercontent.com/5698157/199140853-d4f2e043-2fc4-4ab7-aca8-62587375a82a.png)
